### ISSUE TITLE
Remove “since last Q”

### ISSUE THREAD

**Issue by taterhead247** [F3Nation-Community/weaselbot#15]
In the “haven’t q’d in a while” portion of the kotter report it indicates how many days it’s been since the last Q. It says “(50 days since last Q)”. Can we get rid of “since last Q” and just have the number? That text is implied but makes it harder for the eye to find the number, which is the important part.

**Comment by jasheldo** [comment]
Done in commit 7aeac512ad0e06a54e47a72bf71fd5635b661c51
