### ISSUE TITLE
Allow for custom kotter thresholds

### ISSUE THREAD

**Issue by evanpetzoldt** [F3Nation-Community/weaselbot#5]
I would like to make the length of time of inactivity that makes someone a "kotter" be configurable for each region.

**Comment by jasheldo** [comment]
One idea is to make a threshold table in the weaselshaker schema. Columns would be something like this:

thresholds.no_post
threshold.reminder_weeks
threshold.home_ao_capture
threhold.no_q_weeks
threshold.no_q_posts
threshold.region_name

Each record is a region. Before looping over each region individually, pull this table as its own pandas data frame, say df_threshold. Then, for each region in the loop, use that record from the table to do your analysis and summaries. Happy to do it if you'd like. I can add it to my PR request.
